name: CD Workflow

on: 
  push:
  branches:
    - main


jobs:
  deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.9'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Application
      run: |
        # Add your deployment scripts here (e.g., SSH to serve and pull latest code)
        # Or use a service like Heroku, AWS, or DigitalOcean for deployment
        echo "Deploying FastAPI application..."

    - name: Restart application
      run: |
        # Restart the FastAPI application (e.g., using PM2 or systemd)
        echo "Restarting FastAPI app"